<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Country;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $countries = [
            "BD" => ["name" => "Bangladesh", "iso_code_cca3" => "BGD"],
            "BE" => ["name" => "Belgium", "iso_code_cca3" => "BEL"],
            "BF" => ["name" => "Burkina Faso", "iso_code_cca3" => "BFA"],
            "BG" => ["name" => "Bulgaria", "iso_code_cca3" => "BGR"],
            "BA" => ["name" => "Bosnia and Herzegovina", "iso_code_cca3" => "BIH"],
            "BB" => ["name" => "Barbados", "iso_code_cca3" => "BRB"],
            "WF" => ["name" => "Wallis and Futuna", "iso_code_cca3" => "WLF"],
            "BL" => ["name" => "Saint Barthelemy", "iso_code_cca3" => "BLM"],
            "BM" => ["name" => "Bermuda", "iso_code_cca3" => "BMU"],
            "BN" => ["name" => "Brunei", "iso_code_cca3" => "BRN"],
            "BO" => ["name" => "Bolivia", "iso_code_cca3" => "BOL"],
            "BH" => ["name" => "Bahrain", "iso_code_cca3" => "BHR"],
            "BI" => ["name" => "Burundi", "iso_code_cca3" => "BDI"],
            "BJ" => ["name" => "Benin", "iso_code_cca3" => "BEN"],
            "BT" => ["name" => "Bhutan", "iso_code_cca3" => "BTN"],
            "JM" => ["name" => "Jamaica", "iso_code_cca3" => "JAM"],
            "BV" => ["name" => "Bouvet Island", "iso_code_cca3" => "BVT"],
            "BW" => ["name" => "Botswana", "iso_code_cca3" => "BWA"],
            "WS" => ["name" => "Samoa", "iso_code_cca3" => "WSM"],
            "BQ" => ["name" => "Bonaire, Saint Eustatius and Saba ", "iso_code_cca3" => "BES"],
            "BR" => ["name" => "Brazil", "iso_code_cca3" => "BRA"],
            "BS" => ["name" => "Bahamas", "iso_code_cca3" => "BHS"],
            "JE" => ["name" => "Jersey", "iso_code_cca3" => "JEY"],
            "BY" => ["name" => "Belarus", "iso_code_cca3" => "BLR"],
            "BZ" => ["name" => "Belize", "iso_code_cca3" => "BLZ"],
            "RU" => ["name" => "Russia", "iso_code_cca3" => "RUS"],
            "RW" => ["name" => "Rwanda", "iso_code_cca3" => "RWA"],
            "RS" => ["name" => "Serbia", "iso_code_cca3" => "SRB"],
            "TL" => ["name" => "East Timor", "iso_code_cca3" => "TLS"],
            "RE" => ["name" => "Reunion", "iso_code_cca3" => "REU"],
            "TM" => ["name" => "Turkmenistan", "iso_code_cca3" => "TKM"],
            "TJ" => ["name" => "Tajikistan", "iso_code_cca3" => "TJK"],
            "RO" => ["name" => "Romania", "iso_code_cca3" => "ROU"],
            "TK" => ["name" => "Tokelau", "iso_code_cca3" => "TKL"],
            "GW" => ["name" => "Guinea-Bissau", "iso_code_cca3" => "GNB"],
            "GU" => ["name" => "Guam", "iso_code_cca3" => "GUM"],
            "GT" => ["name" => "Guatemala", "iso_code_cca3" => "GTM"],
            "GS" => ["name" => "South Georgia and the South Sandwich Islands", "iso_code_cca3" => "SGS"],
            "GR" => ["name" => "Greece", "iso_code_cca3" => "GRC"],
            "GQ" => ["name" => "Equatorial Guinea", "iso_code_cca3" => "GNQ"],
            "GP" => ["name" => "Guadeloupe", "iso_code_cca3" => "GLP"],
            "JP" => ["name" => "Japan", "iso_code_cca3" => "JPN"],
            "GY" => ["name" => "Guyana", "iso_code_cca3" => "GUY"],
            "GG" => ["name" => "Guernsey", "iso_code_cca3" => "GGY"],
            "GF" => ["name" => "French Guiana", "iso_code_cca3" => "GUF"],
            "GE" => ["name" => "Georgia", "iso_code_cca3" => "GEO"],
            "GD" => ["name" => "Grenada", "iso_code_cca3" => "GRD"],
            "GB" => ["name" => "United Kingdom", "iso_code_cca3" => "GBR"],
            "GA" => ["name" => "Gabon", "iso_code_cca3" => "GAB"],
            "SV" => ["name" => "El Salvador", "iso_code_cca3" => "SLV"],
            "GN" => ["name" => "Guinea", "iso_code_cca3" => "GIN"],
            "GM" => ["name" => "Gambia", "iso_code_cca3" => "GMB"],
            "GL" => ["name" => "Greenland", "iso_code_cca3" => "GRL"],
            "GI" => ["name" => "Gibraltar", "iso_code_cca3" => "GIB"],
            "GH" => ["name" => "Ghana", "iso_code_cca3" => "GHA"],
            "OM" => ["name" => "Oman", "iso_code_cca3" => "OMN"],
            "TN" => ["name" => "Tunisia", "iso_code_cca3" => "TUN"],
            "JO" => ["name" => "Jordan", "iso_code_cca3" => "JOR"],
            "HR" => ["name" => "Croatia", "iso_code_cca3" => "HRV"],
            "HT" => ["name" => "Haiti", "iso_code_cca3" => "HTI"],
            "HU" => ["name" => "Hungary", "iso_code_cca3" => "HUN"],
            "HK" => ["name" => "Hong Kong", "iso_code_cca3" => "HKG"],
            "HN" => ["name" => "Honduras", "iso_code_cca3" => "HND"],
            "HM" => ["name" => "Heard Island and McDonald Islands", "iso_code_cca3" => "HMD"],
            "VE" => ["name" => "Venezuela", "iso_code_cca3" => "VEN"],
            "PR" => ["name" => "Puerto Rico", "iso_code_cca3" => "PRI"],
            "PS" => ["name" => "Palestinian Territory", "iso_code_cca3" => "PSE"],
            "PW" => ["name" => "Palau", "iso_code_cca3" => "PLW"],
            "PT" => ["name" => "Portugal", "iso_code_cca3" => "PRT"],
            "SJ" => ["name" => "Svalbard and Jan Mayen", "iso_code_cca3" => "SJM"],
            "PY" => ["name" => "Paraguay", "iso_code_cca3" => "PRY"],
            "IQ" => ["name" => "Iraq", "iso_code_cca3" => "IRQ"],
            "PA" => ["name" => "Panama", "iso_code_cca3" => "PAN"],
            "PF" => ["name" => "French Polynesia", "iso_code_cca3" => "PYF"],
            "PG" => ["name" => "Papua New Guinea", "iso_code_cca3" => "PNG"],
            "PE" => ["name" => "Peru", "iso_code_cca3" => "PER"],
            "PK" => ["name" => "Pakistan", "iso_code_cca3" => "PAK"],
            "PH" => ["name" => "Philippines", "iso_code_cca3" => "PHL"],
            "PN" => ["name" => "Pitcairn", "iso_code_cca3" => "PCN"],
            "PL" => ["name" => "Poland", "iso_code_cca3" => "POL"],
            "PM" => ["name" => "Saint Pierre and Miquelon", "iso_code_cca3" => "SPM"],
            "ZM" => ["name" => "Zambia", "iso_code_cca3" => "ZMB"],
            "EH" => ["name" => "Western Sahara", "iso_code_cca3" => "ESH"],
            "EE" => ["name" => "Estonia", "iso_code_cca3" => "EST"],
            "EG" => ["name" => "Egypt", "iso_code_cca3" => "EGY"],
            "ZA" => ["name" => "South Africa", "iso_code_cca3" => "ZAF"],
            "EC" => ["name" => "Ecuador", "iso_code_cca3" => "ECU"],
            "IT" => ["name" => "Italy", "iso_code_cca3" => "ITA"],
            "VN" => ["name" => "Vietnam", "iso_code_cca3" => "VNM"],
            "SB" => ["name" => "Solomon Islands", "iso_code_cca3" => "SLB"],
            "ET" => ["name" => "Ethiopia", "iso_code_cca3" => "ETH"],
            "SO" => ["name" => "Somalia", "iso_code_cca3" => "SOM"],
            "ZW" => ["name" => "Zimbabwe", "iso_code_cca3" => "ZWE"],
            "SA" => ["name" => "Saudi Arabia", "iso_code_cca3" => "SAU"],
            "ES" => ["name" => "Spain", "iso_code_cca3" => "ESP"],
            "ER" => ["name" => "Eritrea", "iso_code_cca3" => "ERI"],
            "ME" => ["name" => "Montenegro", "iso_code_cca3" => "MNE"],
            "MD" => ["name" => "Moldova", "iso_code_cca3" => "MDA"],
            "MG" => ["name" => "Madagascar", "iso_code_cca3" => "MDG"],
            "MF" => ["name" => "Saint Martin", "iso_code_cca3" => "MAF"],
            "MA" => ["name" => "Morocco", "iso_code_cca3" => "MAR"],
            "MC" => ["name" => "Monaco", "iso_code_cca3" => "MCO"],
            "UZ" => ["name" => "Uzbekistan", "iso_code_cca3" => "UZB"],
            "MM" => ["name" => "Myanmar", "iso_code_cca3" => "MMR"],
            "ML" => ["name" => "Mali", "iso_code_cca3" => "MLI"],
            "MO" => ["name" => "Macao", "iso_code_cca3" => "MAC"],
            "MN" => ["name" => "Mongolia", "iso_code_cca3" => "MNG"],
            "MH" => ["name" => "Marshall Islands", "iso_code_cca3" => "MHL"],
            "MK" => ["name" => "Macedonia", "iso_code_cca3" => "MKD"],
            "MU" => ["name" => "Mauritius", "iso_code_cca3" => "MUS"],
            "MT" => ["name" => "Malta", "iso_code_cca3" => "MLT"],
            "MW" => ["name" => "Malawi", "iso_code_cca3" => "MWI"],
            "MV" => ["name" => "Maldives", "iso_code_cca3" => "MDV"],
            "MQ" => ["name" => "Martinique", "iso_code_cca3" => "MTQ"],
            "MP" => ["name" => "Northern Mariana Islands", "iso_code_cca3" => "MNP"],
            "MS" => ["name" => "Montserrat", "iso_code_cca3" => "MSR"],
            "MR" => ["name" => "Mauritania", "iso_code_cca3" => "MRT"],
            "IM" => ["name" => "Isle of Man", "iso_code_cca3" => "IMN"],
            "UG" => ["name" => "Uganda", "iso_code_cca3" => "UGA"],
            "TZ" => ["name" => "Tanzania", "iso_code_cca3" => "TZA"],
            "MY" => ["name" => "Malaysia", "iso_code_cca3" => "MYS"],
            "MX" => ["name" => "Mexico", "iso_code_cca3" => "MEX"],
            "IL" => ["name" => "Israel", "iso_code_cca3" => "ISR"],
            "FR" => ["name" => "France", "iso_code_cca3" => "FRA"],
            "IO" => ["name" => "British Indian Ocean Territory", "iso_code_cca3" => "IOT"],
            "SH" => ["name" => "Saint Helena", "iso_code_cca3" => "SHN"],
            "FI" => ["name" => "Finland", "iso_code_cca3" => "FIN"],
            "FJ" => ["name" => "Fiji", "iso_code_cca3" => "FJI"],
            "FK" => ["name" => "Falkland Islands", "iso_code_cca3" => "FLK"],
            "FM" => ["name" => "Micronesia", "iso_code_cca3" => "FSM"],
            "FO" => ["name" => "Faroe Islands", "iso_code_cca3" => "FRO"],
            "NI" => ["name" => "Nicaragua", "iso_code_cca3" => "NIC"],
            "NL" => ["name" => "Netherlands", "iso_code_cca3" => "NLD"],
            "NO" => ["name" => "Norway", "iso_code_cca3" => "NOR"],
            "NA" => ["name" => "Namibia", "iso_code_cca3" => "NAM"],
            "VU" => ["name" => "Vanuatu", "iso_code_cca3" => "VUT"],
            "NC" => ["name" => "New Caledonia", "iso_code_cca3" => "NCL"],
            "NE" => ["name" => "Niger", "iso_code_cca3" => "NER"],
            "NF" => ["name" => "Norfolk Island", "iso_code_cca3" => "NFK"],
            "NG" => ["name" => "Nigeria", "iso_code_cca3" => "NGA"],
            "NZ" => ["name" => "New Zealand", "iso_code_cca3" => "NZL"],
            "NP" => ["name" => "Nepal", "iso_code_cca3" => "NPL"],
            "NR" => ["name" => "Nauru", "iso_code_cca3" => "NRU"],
            "NU" => ["name" => "Niue", "iso_code_cca3" => "NIU"],
            "CK" => ["name" => "Cook Islands", "iso_code_cca3" => "COK"],
            "XK" => ["name" => "Kosovo", "iso_code_cca3" => "XKX"],
            "CI" => ["name" => "Ivory Coast", "iso_code_cca3" => "CIV"],
            "CH" => ["name" => "Switzerland", "iso_code_cca3" => "CHE"],
            "CO" => ["name" => "Colombia", "iso_code_cca3" => "COL"],
            "CN" => ["name" => "China", "iso_code_cca3" => "CHN"],
            "CM" => ["name" => "Cameroon", "iso_code_cca3" => "CMR"],
            "CL" => ["name" => "Chile", "iso_code_cca3" => "CHL"],
            "CC" => ["name" => "Cocos Islands", "iso_code_cca3" => "CCK"],
            "CA" => ["name" => "Canada", "iso_code_cca3" => "CAN"],
            "CG" => ["name" => "Republic of the Congo", "iso_code_cca3" => "COG"],
            "CF" => ["name" => "Central African Republic", "iso_code_cca3" => "CAF"],
            "CD" => ["name" => "Democratic Republic of the Congo", "iso_code_cca3" => "COD"],
            "CZ" => ["name" => "Czech Republic", "iso_code_cca3" => "CZE"],
            "CY" => ["name" => "Cyprus", "iso_code_cca3" => "CYP"],
            "CX" => ["name" => "Christmas Island", "iso_code_cca3" => "CXR"],
            "CR" => ["name" => "Costa Rica", "iso_code_cca3" => "CRI"],
            "CW" => ["name" => "Curacao", "iso_code_cca3" => "CUW"],
            "CV" => ["name" => "Cape Verde", "iso_code_cca3" => "CPV"],
            "CU" => ["name" => "Cuba", "iso_code_cca3" => "CUB"],
            "SZ" => ["name" => "Swaziland", "iso_code_cca3" => "SWZ"],
            "SY" => ["name" => "Syria", "iso_code_cca3" => "SYR"],
            "SX" => ["name" => "Sint Maarten", "iso_code_cca3" => "SXM"],
            "KG" => ["name" => "Kyrgyzstan", "iso_code_cca3" => "KGZ"],
            "KE" => ["name" => "Kenya", "iso_code_cca3" => "KEN"],
            "SS" => ["name" => "South Sudan", "iso_code_cca3" => "SSD"],
            "SR" => ["name" => "Suriname", "iso_code_cca3" => "SUR"],
            "KI" => ["name" => "Kiribati", "iso_code_cca3" => "KIR"],
            "KH" => ["name" => "Cambodia", "iso_code_cca3" => "KHM"],
            "KN" => ["name" => "Saint Kitts and Nevis", "iso_code_cca3" => "KNA"],
            "KM" => ["name" => "Comoros", "iso_code_cca3" => "COM"],
            "ST" => ["name" => "Sao Tome and Principe", "iso_code_cca3" => "STP"],
            "SK" => ["name" => "Slovakia", "iso_code_cca3" => "SVK"],
            "KR" => ["name" => "South Korea", "iso_code_cca3" => "KOR"],
            "SI" => ["name" => "Slovenia", "iso_code_cca3" => "SVN"],
            "KP" => ["name" => "North Korea", "iso_code_cca3" => "PRK"],
            "KW" => ["name" => "Kuwait", "iso_code_cca3" => "KWT"],
            "SN" => ["name" => "Senegal", "iso_code_cca3" => "SEN"],
            "SM" => ["name" => "San Marino", "iso_code_cca3" => "SMR"],
            "SL" => ["name" => "Sierra Leone", "iso_code_cca3" => "SLE"],
            "SC" => ["name" => "Seychelles", "iso_code_cca3" => "SYC"],
            "KZ" => ["name" => "Kazakhstan", "iso_code_cca3" => "KAZ"],
            "KY" => ["name" => "Cayman Islands", "iso_code_cca3" => "CYM"],
            "SG" => ["name" => "Singapore", "iso_code_cca3" => "SGP"],
            "SE" => ["name" => "Sweden", "iso_code_cca3" => "SWE"],
            "SD" => ["name" => "Sudan", "iso_code_cca3" => "SDN"],
            "DO" => ["name" => "Dominican Republic", "iso_code_cca3" => "DOM"],
            "DM" => ["name" => "Dominica", "iso_code_cca3" => "DMA"],
            "DJ" => ["name" => "Djibouti", "iso_code_cca3" => "DJI"],
            "DK" => ["name" => "Denmark", "iso_code_cca3" => "DNK"],
            "VG" => ["name" => "British Virgin Islands", "iso_code_cca3" => "VGB"],
            "DE" => ["name" => "Germany", "iso_code_cca3" => "DEU"],
            "YE" => ["name" => "Yemen", "iso_code_cca3" => "YEM"],
            "DZ" => ["name" => "Algeria", "iso_code_cca3" => "DZA"],
            "US" => ["name" => "United States", "iso_code_cca3" => "USA"],
            "UY" => ["name" => "Uruguay", "iso_code_cca3" => "URY"],
            "YT" => ["name" => "Mayotte", "iso_code_cca3" => "MYT"],
            "UM" => ["name" => "United States Minor Outlying Islands", "iso_code_cca3" => "UMI"],
            "LB" => ["name" => "Lebanon", "iso_code_cca3" => "LBN"],
            "LC" => ["name" => "Saint Lucia", "iso_code_cca3" => "LCA"],
            "LA" => ["name" => "Laos", "iso_code_cca3" => "LAO"],
            "TV" => ["name" => "Tuvalu", "iso_code_cca3" => "TUV"],
            "TW" => ["name" => "Taiwan", "iso_code_cca3" => "TWN"],
            "TT" => ["name" => "Trinidad and Tobago", "iso_code_cca3" => "TTO"],
            "TR" => ["name" => "Turkey", "iso_code_cca3" => "TUR"],
            "LK" => ["name" => "Sri Lanka", "iso_code_cca3" => "LKA"],
            "LI" => ["name" => "Liechtenstein", "iso_code_cca3" => "LIE"],
            "LV" => ["name" => "Latvia", "iso_code_cca3" => "LVA"],
            "TO" => ["name" => "Tonga", "iso_code_cca3" => "TON"],
            "LT" => ["name" => "Lithuania", "iso_code_cca3" => "LTU"],
            "LU" => ["name" => "Luxembourg", "iso_code_cca3" => "LUX"],
            "LR" => ["name" => "Liberia", "iso_code_cca3" => "LBR"],
            "LS" => ["name" => "Lesotho", "iso_code_cca3" => "LSO"],
            "TH" => ["name" => "Thailand", "iso_code_cca3" => "THA"],
            "TF" => ["name" => "French Southern Territories", "iso_code_cca3" => "ATF"],
            "TG" => ["name" => "Togo", "iso_code_cca3" => "TGO"],
            "TD" => ["name" => "Chad", "iso_code_cca3" => "TCD"],
            "TC" => ["name" => "Turks and Caicos Islands", "iso_code_cca3" => "TCA"],
            "LY" => ["name" => "Libya", "iso_code_cca3" => "LBY"],
            "VA" => ["name" => "Vatican", "iso_code_cca3" => "VAT"],
            "VC" => ["name" => "Saint Vincent and the Grenadines", "iso_code_cca3" => "VCT"],
            "AE" => ["name" => "United Arab Emirates", "iso_code_cca3" => "ARE"],
            "AD" => ["name" => "Andorra", "iso_code_cca3" => "AND"],
            "AG" => ["name" => "Antigua and Barbuda", "iso_code_cca3" => "ATG"],
            "AF" => ["name" => "Afghanistan", "iso_code_cca3" => "AFG"],
            "AI" => ["name" => "Anguilla", "iso_code_cca3" => "AIA"],
            "VI" => ["name" => "U.S. Virgin Islands", "iso_code_cca3" => "VIR"],
            "IS" => ["name" => "Iceland", "iso_code_cca3" => "ISL"],
            "IR" => ["name" => "Iran", "iso_code_cca3" => "IRN"],
            "AM" => ["name" => "Armenia", "iso_code_cca3" => "ARM"],
            "AL" => ["name" => "Albania", "iso_code_cca3" => "ALB"],
            "AO" => ["name" => "Angola", "iso_code_cca3" => "AGO"],
            "AQ" => ["name" => "Antarctica", "iso_code_cca3" => "ATA"],
            "AS" => ["name" => "American Samoa", "iso_code_cca3" => "ASM"],
            "AR" => ["name" => "Argentina", "iso_code_cca3" => "ARG"],
            "AU" => ["name" => "Australia", "iso_code_cca3" => "AUS"],
            "AT" => ["name" => "Austria", "iso_code_cca3" => "AUT"],
            "AW" => ["name" => "Aruba", "iso_code_cca3" => "ABW"],
            "IN" => ["name" => "India", "iso_code_cca3" => "IND"],
            "AX" => ["name" => "Aland Islands", "iso_code_cca3" => "ALA"],
            "AZ" => ["name" => "Azerbaijan", "iso_code_cca3" => "AZE"],
            "IE" => ["name" => "Ireland", "iso_code_cca3" => "IRL"],
            "ID" => ["name" => "Indonesia", "iso_code_cca3" => "IDN"],
            "UA" => ["name" => "Ukraine", "iso_code_cca3" => "UKR"],
            "QA" => ["name" => "Qatar", "iso_code_cca3" => "QAT"],
            "MZ" => ["name" => "Mozambique", "iso_code_cca3" => "MOZ"]
        ];



        DB::transaction(function () use ($countries) {
            foreach ($countries as $key => $value) {
                Country::updateOrCreate(
                    ['iso_code_cca2' => $key, 'iso_code_cca3' => $value['iso_code_cca3']],
                    ['name' => $value["name"]]
                );
            }
        });
    }
}
